name: controller
on:
  pull_request_target:
    types: [ opened, edited, synchronize, reopened, ready_for_review ]
  merge_group:
    types: [ checks_requested ]

jobs:
  run-workflows:
    runs-on: [ self-hosted, solinas ]
    outputs:
      files: ${{ steps.pathFilters.outputs.changes }}
    steps:
      - name: Checkout PR merge commit
        id: checkout_pr_merge_commit
        uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: pathFilters
        with:
          filters: .github/controller-filters.yaml

  unittest:
    uses: ./.github/workflows/unit-test-go.yml
    needs: run-workflows
    if: ${{ contains(needs.run-workflows.outputs.files, 'unitTestsFileChanges') }}
  hadolint:
    uses: ./.github/workflows/validate-dockerfiles.yml
    needs: run-workflows
    if: ${{ contains(needs.run-workflows.outputs.files, 'dockerFileChanges') }}
  build-test-image:
    uses: ./.github/workflows/build-test-image.yml
    needs: run-workflows
    if: ${{ contains(needs.run-workflows.outputs.files, 'buildImageFileChanges') }}