name: unit-test-go

on:
  workflow_call:

jobs:
  unittest:
    runs-on: ubuntu-latest
    env:
      GOPRIVATE: github.tools.sap
    steps:
      - name: Verify merge commit sha
        id: verify_merge_commit_sha
        run: |
          if [ -z "${{ github.event.pull_request.merge_commit_sha }}" ]; then
            echo "::error title=PR Commit Merge Error::The pull request does not have a merge commit SHA. Skipping the workflow. Please create a new empty commit using the --allow-empty flag and try again."
            exit 1
          fi
        if: ${{ github.event_name == 'pull_request_target' }}
      - name: Checkout PR merge commit
        id: checkout_pr_merge_commit
        uses: actions/checkout@v4
        with:
          ref: "${{ github.event.pull_request.merge_commit_sha }}"
        if: ${{ github.event_name == 'pull_request_target' }}
      - name: Checkout target branch
        id: checkout_target_branch
        uses: actions/checkout@v4
        if: ${{ github.event_name == 'merge_group' }}
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.2'
      - name: Setup authentication for private Go modules
        run: |
          echo "machine github.tools.sap" >> ~/.netrc
          echo "login $GITHUB_ACTOR" >> ~/.netrc
          echo "password ${{ secrets.GITHUB_TOKEN }}" >> ~/.netrc
          chmod 600 ~/.netrc
      - name: Install dependencies
        run: go mod tidy
      - name: Run unit tests
        run: go test -cover ./...
